name: binate_digital_reusable_widgets
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/FUZAIL-GIT/binate-digital-reusables-widgets

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  skeletonizer: ^1.4.3
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
